// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/currency/presentation/bloc/currency_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:finance_tracker/core/errors/failures.dart' as _i6;
import 'package:finance_tracker/features/currency/domain/entities/currency.dart'
    as _i7;
import 'package:finance_tracker/features/currency/domain/entities/exchange_rate.dart'
    as _i9;
import 'package:finance_tracker/features/currency/domain/repositories/currency_repository.dart'
    as _i2;
import 'package:finance_tracker/features/currency/domain/usecases/convert_currency.dart'
    as _i10;
import 'package:finance_tracker/features/currency/domain/usecases/get_base_currency.dart'
    as _i11;
import 'package:finance_tracker/features/currency/domain/usecases/get_currencies.dart'
    as _i4;
import 'package:finance_tracker/features/currency/domain/usecases/get_exchange_rates.dart'
    as _i8;
import 'package:finance_tracker/features/currency/domain/usecases/update_base_currency.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCurrencyRepository_0 extends _i1.SmartFake
    implements _i2.CurrencyRepository {
  _FakeCurrencyRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCurrencies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrencies extends _i1.Mock implements _i4.GetCurrencies {
  MockGetCurrencies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CurrencyRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCurrencyRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CurrencyRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Currency>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Currency>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Currency>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Currency>>>);
}

/// A class which mocks [GetExchangeRates].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExchangeRates extends _i1.Mock implements _i8.GetExchangeRates {
  MockGetExchangeRates() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CurrencyRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCurrencyRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CurrencyRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.ExchangeRate>>> call(
          _i8.GetExchangeRatesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i9.ExchangeRate>>>.value(
                _FakeEither_1<_i6.Failure, List<_i9.ExchangeRate>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i9.ExchangeRate>>>);
}

/// A class which mocks [ConvertCurrency].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvertCurrency extends _i1.Mock implements _i10.ConvertCurrency {
  MockConvertCurrency() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CurrencyRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCurrencyRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CurrencyRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, double>> call(
          _i10.ConvertCurrencyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, double>>.value(
            _FakeEither_1<_i6.Failure, double>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, double>>);
}

/// A class which mocks [GetBaseCurrency].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBaseCurrency extends _i1.Mock implements _i11.GetBaseCurrency {
  MockGetBaseCurrency() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CurrencyRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCurrencyRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CurrencyRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(
          _i11.GetBaseCurrencyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [UpdateBaseCurrency].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateBaseCurrency extends _i1.Mock
    implements _i12.UpdateBaseCurrency {
  MockUpdateBaseCurrency() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CurrencyRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCurrencyRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CurrencyRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i12.UpdateBaseCurrencyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
