// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/reports/domain/usecases/get_expense_breakdown_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finance_tracker/core/errors/failures.dart' as _i5;
import 'package:finance_tracker/features/reports/domain/entities/expense_breakdown.dart'
    as _i6;
import 'package:finance_tracker/features/reports/domain/entities/financial_trends.dart'
    as _i7;
import 'package:finance_tracker/features/reports/domain/entities/monthly_comparison.dart'
    as _i8;
import 'package:finance_tracker/features/reports/domain/repositories/reports_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReportsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportsRepository extends _i1.Mock implements _i3.ReportsRepository {
  MockReportsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ExpenseBreakdown>>
      getExpenseBreakdown({
    required String? userId,
    required DateTime? startDate,
    required DateTime? endDate,
    String? currencyCode = r'USD',
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getExpenseBreakdown,
              [],
              {
                #userId: userId,
                #startDate: startDate,
                #endDate: endDate,
                #currencyCode: currencyCode,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ExpenseBreakdown>>.value(
                    _FakeEither_0<_i5.Failure, _i6.ExpenseBreakdown>(
              this,
              Invocation.method(
                #getExpenseBreakdown,
                [],
                {
                  #userId: userId,
                  #startDate: startDate,
                  #endDate: endDate,
                  #currencyCode: currencyCode,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ExpenseBreakdown>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.FinancialTrends>> getFinancialTrends({
    required String? userId,
    required DateTime? startDate,
    required DateTime? endDate,
    String? groupBy = r'month',
    String? currencyCode = r'USD',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFinancialTrends,
          [],
          {
            #userId: userId,
            #startDate: startDate,
            #endDate: endDate,
            #groupBy: groupBy,
            #currencyCode: currencyCode,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.FinancialTrends>>.value(
                _FakeEither_0<_i5.Failure, _i7.FinancialTrends>(
          this,
          Invocation.method(
            #getFinancialTrends,
            [],
            {
              #userId: userId,
              #startDate: startDate,
              #endDate: endDate,
              #groupBy: groupBy,
              #currencyCode: currencyCode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.FinancialTrends>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i8.MonthlyComparison>> getMonthlyComparison({
    required String? userId,
    int? monthCount = 6,
    String? currencyCode = r'USD',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyComparison,
          [],
          {
            #userId: userId,
            #monthCount: monthCount,
            #currencyCode: currencyCode,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.MonthlyComparison>>.value(
                _FakeEither_0<_i5.Failure, _i8.MonthlyComparison>(
          this,
          Invocation.method(
            #getMonthlyComparison,
            [],
            {
              #userId: userId,
              #monthCount: monthCount,
              #currencyCode: currencyCode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.MonthlyComparison>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> exportReportToCsv({
    required String? userId,
    required String? reportType,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportReportToCsv,
          [],
          {
            #userId: userId,
            #reportType: reportType,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #exportReportToCsv,
            [],
            {
              #userId: userId,
              #reportType: reportType,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
