// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/currency/domain/usecases/get_currencies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finance_tracker/core/errors/failures.dart' as _i5;
import 'package:finance_tracker/features/currency/domain/entities/currency.dart'
    as _i6;
import 'package:finance_tracker/features/currency/domain/entities/exchange_rate.dart'
    as _i7;
import 'package:finance_tracker/features/currency/domain/repositories/currency_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i3.CurrencyRepository {
  MockCurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Currency>>> getCurrencies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrencies,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Currency>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Currency>>(
          this,
          Invocation.method(
            #getCurrencies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Currency>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Currency>> getCurrencyByCode(
          String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrencyByCode,
          [code],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Currency>>.value(
            _FakeEither_0<_i5.Failure, _i6.Currency>(
          this,
          Invocation.method(
            #getCurrencyByCode,
            [code],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Currency>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ExchangeRate>>> getExchangeRates(
          {String? baseCurrency}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExchangeRates,
          [],
          {#baseCurrency: baseCurrency},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.ExchangeRate>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.ExchangeRate>>(
          this,
          Invocation.method(
            #getExchangeRates,
            [],
            {#baseCurrency: baseCurrency},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ExchangeRate>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ExchangeRate>> getExchangeRate({
    required String? fromCurrency,
    required String? toCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExchangeRate,
          [],
          {
            #fromCurrency: fromCurrency,
            #toCurrency: toCurrency,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.ExchangeRate>>.value(
                _FakeEither_0<_i5.Failure, _i7.ExchangeRate>(
          this,
          Invocation.method(
            #getExchangeRate,
            [],
            {
              #fromCurrency: fromCurrency,
              #toCurrency: toCurrency,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ExchangeRate>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> convertCurrency({
    required double? amount,
    required String? fromCurrency,
    required String? toCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertCurrency,
          [],
          {
            #amount: amount,
            #fromCurrency: fromCurrency,
            #toCurrency: toCurrency,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #convertCurrency,
            [],
            {
              #amount: amount,
              #fromCurrency: fromCurrency,
              #toCurrency: toCurrency,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getBaseCurrency(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBaseCurrency,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #getBaseCurrency,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateBaseCurrency({
    required String? userId,
    required String? currencyCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBaseCurrency,
          [],
          {
            #userId: userId,
            #currencyCode: currencyCode,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateBaseCurrency,
            [],
            {
              #userId: userId,
              #currencyCode: currencyCode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> refreshExchangeRates() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshExchangeRates,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #refreshExchangeRates,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
