// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/transactions/domain/usecases/update_transaction_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finance_tracker/core/errors/failures.dart' as _i5;
import 'package:finance_tracker/features/transactions/domain/entities/transaction.dart'
    as _i6;
import 'package:finance_tracker/features/transactions/domain/repositories/transaction_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i3.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>> getTransactions(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
          this,
          Invocation.method(
            #getTransactions,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>> getTransactionById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>>.value(
            _FakeEither_0<_i5.Failure, _i6.Transaction>(
          this,
          Invocation.method(
            #getTransactionById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>> createTransaction(
          _i6.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>>.value(
            _FakeEither_0<_i5.Failure, _i6.Transaction>(
          this,
          Invocation.method(
            #createTransaction,
            [transaction],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>> updateTransaction(
          _i6.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>>.value(
            _FakeEither_0<_i5.Failure, _i6.Transaction>(
          this,
          Invocation.method(
            #updateTransaction,
            [transaction],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Transaction>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTransaction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteTransaction,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.Transaction>>> filterTransactions({
    required String? userId,
    DateTime? startDate,
    DateTime? endDate,
    String? accountId,
    String? categoryId,
    _i6.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterTransactions,
          [],
          {
            #userId: userId,
            #startDate: startDate,
            #endDate: endDate,
            #accountId: accountId,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
          this,
          Invocation.method(
            #filterTransactions,
            [],
            {
              #userId: userId,
              #startDate: startDate,
              #endDate: endDate,
              #accountId: accountId,
              #categoryId: categoryId,
              #type: type,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.Transaction>>> searchTransactions({
    required String? userId,
    required String? query,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTransactions,
          [],
          {
            #userId: userId,
            #query: query,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
          this,
          Invocation.method(
            #searchTransactions,
            [],
            {
              #userId: userId,
              #query: query,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>
      getTransactionsByAccount(String? accountId) => (super.noSuchMethod(
            Invocation.method(
              #getTransactionsByAccount,
              [accountId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
              this,
              Invocation.method(
                #getTransactionsByAccount,
                [accountId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>
      getTransactionsByCategory(String? categoryId) => (super.noSuchMethod(
            Invocation.method(
              #getTransactionsByCategory,
              [categoryId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
              this,
              Invocation.method(
                #getTransactionsByCategory,
                [categoryId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>
      getTransactionsByDateRange({
    required String? userId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTransactionsByDateRange,
              [],
              {
                #userId: userId,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
              this,
              Invocation.method(
                #getTransactionsByDateRange,
                [],
                {
                  #userId: userId,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getTotalByType({
    required String? userId,
    required _i6.TransactionType? type,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalByType,
          [],
          {
            #userId: userId,
            #type: type,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getTotalByType,
            [],
            {
              #userId: userId,
              #type: type,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.Transaction>>> getRecentTransactions({
    required String? userId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentTransactions,
          [],
          {
            #userId: userId,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
          this,
          Invocation.method(
            #getRecentTransactions,
            [],
            {
              #userId: userId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);
}
