// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/accounts/domain/usecases/get_account_by_id_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finance_tracker/core/errors/failures.dart' as _i5;
import 'package:finance_tracker/features/accounts/domain/entities/account.dart'
    as _i6;
import 'package:finance_tracker/features/accounts/domain/repositories/account_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i3.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>> getAccounts({
    required String? userId,
    bool? activeOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccounts,
          [],
          {
            #userId: userId,
            #activeOnly: activeOnly,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Account>>(
          this,
          Invocation.method(
            #getAccounts,
            [],
            {
              #userId: userId,
              #activeOnly: activeOnly,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Account>> getAccountById(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountById,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>.value(
            _FakeEither_0<_i5.Failure, _i6.Account>(
          this,
          Invocation.method(
            #getAccountById,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Account>> createAccount({
    required String? userId,
    required String? name,
    required _i6.AccountType? type,
    required double? initialBalance,
    required String? currency,
    String? icon,
    String? color,
    String? notes,
    double? creditLimit,
    double? interestRate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [],
          {
            #userId: userId,
            #name: name,
            #type: type,
            #initialBalance: initialBalance,
            #currency: currency,
            #icon: icon,
            #color: color,
            #notes: notes,
            #creditLimit: creditLimit,
            #interestRate: interestRate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>.value(
            _FakeEither_0<_i5.Failure, _i6.Account>(
          this,
          Invocation.method(
            #createAccount,
            [],
            {
              #userId: userId,
              #name: name,
              #type: type,
              #initialBalance: initialBalance,
              #currency: currency,
              #icon: icon,
              #color: color,
              #notes: notes,
              #creditLimit: creditLimit,
              #interestRate: interestRate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Account>> updateAccount({
    required String? accountId,
    String? name,
    _i6.AccountType? type,
    String? currency,
    String? icon,
    String? color,
    bool? isActive,
    String? notes,
    double? creditLimit,
    double? interestRate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [],
          {
            #accountId: accountId,
            #name: name,
            #type: type,
            #currency: currency,
            #icon: icon,
            #color: color,
            #isActive: isActive,
            #notes: notes,
            #creditLimit: creditLimit,
            #interestRate: interestRate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>.value(
            _FakeEither_0<_i5.Failure, _i6.Account>(
          this,
          Invocation.method(
            #updateAccount,
            [],
            {
              #accountId: accountId,
              #name: name,
              #type: type,
              #currency: currency,
              #icon: icon,
              #color: color,
              #isActive: isActive,
              #notes: notes,
              #creditLimit: creditLimit,
              #interestRate: interestRate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Account>> updateBalance({
    required String? accountId,
    required double? newBalance,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBalance,
          [],
          {
            #accountId: accountId,
            #newBalance: newBalance,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>.value(
            _FakeEither_0<_i5.Failure, _i6.Account>(
          this,
          Invocation.method(
            #updateBalance,
            [],
            {
              #accountId: accountId,
              #newBalance: newBalance,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Account>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getTotalBalance({
    required String? userId,
    required String? currency,
    bool? activeOnly = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalBalance,
          [],
          {
            #userId: userId,
            #currency: currency,
            #activeOnly: activeOnly,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getTotalBalance,
            [],
            {
              #userId: userId,
              #currency: currency,
              #activeOnly: activeOnly,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);
}
