// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/budgets/domain/usecases/update_budget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finance_tracker/core/errors/failures.dart' as _i5;
import 'package:finance_tracker/features/budgets/domain/entities/budget.dart'
    as _i6;
import 'package:finance_tracker/features/budgets/domain/entities/budget_usage.dart'
    as _i7;
import 'package:finance_tracker/features/budgets/domain/repositories/budget_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetRepository extends _i1.Mock implements _i3.BudgetRepository {
  MockBudgetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Budget>>> getBudgets({
    required String? userId,
    bool? activeOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgets,
          [],
          {
            #userId: userId,
            #activeOnly: activeOnly,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Budget>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Budget>>(
          this,
          Invocation.method(
            #getBudgets,
            [],
            {
              #userId: userId,
              #activeOnly: activeOnly,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Budget>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>> getBudgetById(
          {required String? budgetId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgetById,
          [],
          {#budgetId: budgetId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>>.value(
            _FakeEither_0<_i5.Failure, _i6.Budget>(
          this,
          Invocation.method(
            #getBudgetById,
            [],
            {#budgetId: budgetId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Budget>>> getBudgetsByCategory(
          {required String? categoryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgetsByCategory,
          [],
          {#categoryId: categoryId},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Budget>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Budget>>(
          this,
          Invocation.method(
            #getBudgetsByCategory,
            [],
            {#categoryId: categoryId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Budget>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>> createBudget(
          {required _i6.Budget? budget}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBudget,
          [],
          {#budget: budget},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>>.value(
            _FakeEither_0<_i5.Failure, _i6.Budget>(
          this,
          Invocation.method(
            #createBudget,
            [],
            {#budget: budget},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>> updateBudget(
          {required _i6.Budget? budget}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBudget,
          [],
          {#budget: budget},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>>.value(
            _FakeEither_0<_i5.Failure, _i6.Budget>(
          this,
          Invocation.method(
            #updateBudget,
            [],
            {#budget: budget},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Budget>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteBudget(
          {required String? budgetId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBudget,
          [],
          {#budgetId: budgetId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteBudget,
            [],
            {#budgetId: budgetId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.BudgetUsage>> calculateBudgetUsage(
          {required String? budgetId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBudgetUsage,
          [],
          {#budgetId: budgetId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.BudgetUsage>>.value(
            _FakeEither_0<_i5.Failure, _i7.BudgetUsage>(
          this,
          Invocation.method(
            #calculateBudgetUsage,
            [],
            {#budgetId: budgetId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.BudgetUsage>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, Map<String, _i7.BudgetUsage>>> getBudgetUsages(
          {required List<String>? budgetIds}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgetUsages,
          [],
          {#budgetIds: budgetIds},
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, Map<String, _i7.BudgetUsage>>>.value(
            _FakeEither_0<_i5.Failure, Map<String, _i7.BudgetUsage>>(
          this,
          Invocation.method(
            #getBudgetUsages,
            [],
            {#budgetIds: budgetIds},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, _i7.BudgetUsage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> shouldAlert(
          {required String? budgetId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldAlert,
          [],
          {#budgetId: budgetId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #shouldAlert,
            [],
            {#budgetId: budgetId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
