// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/recurring_transactions/domain/usecases/create_recurring_transaction_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finance_tracker/core/errors/failures.dart' as _i5;
import 'package:finance_tracker/features/recurring_transactions/domain/entities/recurring_transaction.dart'
    as _i6;
import 'package:finance_tracker/features/recurring_transactions/domain/repositories/recurring_transaction_repository.dart'
    as _i3;
import 'package:finance_tracker/features/transactions/domain/entities/transaction.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RecurringTransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringTransactionRepository extends _i1.Mock
    implements _i3.RecurringTransactionRepository {
  MockRecurringTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>
      getRecurringTransactions({
    required String? userId,
    bool? activeOnly = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecurringTransactions,
              [],
              {
                #userId: userId,
                #activeOnly: activeOnly,
              },
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.RecurringTransaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.RecurringTransaction>>(
              this,
              Invocation.method(
                #getRecurringTransactions,
                [],
                {
                  #userId: userId,
                  #activeOnly: activeOnly,
                },
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RecurringTransaction>>
      getRecurringTransactionById({required String? recurringTransactionId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecurringTransactionById,
              [],
              {#recurringTransactionId: recurringTransactionId},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.RecurringTransaction>>.value(
                _FakeEither_0<_i5.Failure, _i6.RecurringTransaction>(
              this,
              Invocation.method(
                #getRecurringTransactionById,
                [],
                {#recurringTransactionId: recurringTransactionId},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.RecurringTransaction>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>
      getRecurringTransactionsByAccount({required String? accountId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecurringTransactionsByAccount,
              [],
              {#accountId: accountId},
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.RecurringTransaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.RecurringTransaction>>(
              this,
              Invocation.method(
                #getRecurringTransactionsByAccount,
                [],
                {#accountId: accountId},
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>
      getRecurringTransactionsByCategory({required String? categoryId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecurringTransactionsByCategory,
              [],
              {#categoryId: categoryId},
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.RecurringTransaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.RecurringTransaction>>(
              this,
              Invocation.method(
                #getRecurringTransactionsByCategory,
                [],
                {#categoryId: categoryId},
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RecurringTransaction>>
      createRecurringTransaction(
              {required _i6.RecurringTransaction? recurringTransaction}) =>
          (super.noSuchMethod(
            Invocation.method(
              #createRecurringTransaction,
              [],
              {#recurringTransaction: recurringTransaction},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.RecurringTransaction>>.value(
                _FakeEither_0<_i5.Failure, _i6.RecurringTransaction>(
              this,
              Invocation.method(
                #createRecurringTransaction,
                [],
                {#recurringTransaction: recurringTransaction},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.RecurringTransaction>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RecurringTransaction>>
      updateRecurringTransaction(
              {required _i6.RecurringTransaction? recurringTransaction}) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateRecurringTransaction,
              [],
              {#recurringTransaction: recurringTransaction},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.RecurringTransaction>>.value(
                _FakeEither_0<_i5.Failure, _i6.RecurringTransaction>(
              this,
              Invocation.method(
                #updateRecurringTransaction,
                [],
                {#recurringTransaction: recurringTransaction},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.RecurringTransaction>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteRecurringTransaction(
          {required String? recurringTransactionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecurringTransaction,
          [],
          {#recurringTransactionId: recurringTransactionId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteRecurringTransaction,
            [],
            {#recurringTransactionId: recurringTransactionId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>
      getDueRecurringTransactions() => (super.noSuchMethod(
            Invocation.method(
              #getDueRecurringTransactions,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.RecurringTransaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.RecurringTransaction>>(
              this,
              Invocation.method(
                #getDueRecurringTransactions,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.RecurringTransaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Transaction>> generateTransaction({
    required String? recurringTransactionId,
    required DateTime? occurrenceDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateTransaction,
          [],
          {
            #recurringTransactionId: recurringTransactionId,
            #occurrenceDate: occurrenceDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Transaction>>.value(
            _FakeEither_0<_i5.Failure, _i7.Transaction>(
          this,
          Invocation.method(
            #generateTransaction,
            [],
            {
              #recurringTransactionId: recurringTransactionId,
              #occurrenceDate: occurrenceDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Transaction>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Transaction>>>
      processDueRecurringTransactions() => (super.noSuchMethod(
            Invocation.method(
              #processDueRecurringTransactions,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Transaction>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Transaction>>(
              this,
              Invocation.method(
                #processDueRecurringTransactions,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Transaction>>>);
}
