// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/accounts/presentation/bloc/account_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:finance_tracker/core/errors/failures.dart' as _i6;
import 'package:finance_tracker/features/accounts/domain/entities/account.dart'
    as _i7;
import 'package:finance_tracker/features/accounts/domain/repositories/account_repository.dart'
    as _i2;
import 'package:finance_tracker/features/accounts/domain/usecases/create_account.dart'
    as _i9;
import 'package:finance_tracker/features/accounts/domain/usecases/delete_account.dart'
    as _i11;
import 'package:finance_tracker/features/accounts/domain/usecases/get_account_by_id.dart'
    as _i8;
import 'package:finance_tracker/features/accounts/domain/usecases/get_accounts.dart'
    as _i4;
import 'package:finance_tracker/features/accounts/domain/usecases/update_account.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccountRepository_0 extends _i1.SmartFake
    implements _i2.AccountRepository {
  _FakeAccountRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAccounts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAccounts extends _i1.Mock implements _i4.GetAccounts {
  MockGetAccounts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAccountRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AccountRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Account>>> call(
          _i4.GetAccountsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Account>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Account>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Account>>>);
}

/// A class which mocks [GetAccountById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAccountById extends _i1.Mock implements _i8.GetAccountById {
  MockGetAccountById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAccountRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AccountRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Account>> call(
          _i8.GetAccountByIdParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Account>>.value(
            _FakeEither_1<_i6.Failure, _i7.Account>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Account>>);
}

/// A class which mocks [CreateAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAccount extends _i1.Mock implements _i9.CreateAccount {
  MockCreateAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAccountRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AccountRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Account>> call(
          _i9.CreateAccountParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Account>>.value(
            _FakeEither_1<_i6.Failure, _i7.Account>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Account>>);
}

/// A class which mocks [UpdateAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAccount extends _i1.Mock implements _i10.UpdateAccount {
  MockUpdateAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAccountRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AccountRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Account>> call(
          _i10.UpdateAccountParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Account>>.value(
            _FakeEither_1<_i6.Failure, _i7.Account>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Account>>);
}

/// A class which mocks [DeleteAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAccount extends _i1.Mock implements _i11.DeleteAccount {
  MockDeleteAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAccountRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AccountRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i11.DeleteAccountParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
