// Mocks generated by Mockito 5.4.4 from annotations
// in finance_tracker/test/features/data_export/domain/usecases/import_data_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finance_tracker/core/errors/failures.dart' as _i5;
import 'package:finance_tracker/features/data_export/domain/entities/export_format.dart'
    as _i6;
import 'package:finance_tracker/features/data_export/domain/repositories/data_export_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DataExportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataExportRepository extends _i1.Mock
    implements _i3.DataExportRepository {
  MockDataExportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>> exportTransactions({
    required String? userId,
    required _i6.ExportFormat? format,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportTransactions,
          [],
          {
            #userId: userId,
            #format: format,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ExportResult>(
          this,
          Invocation.method(
            #exportTransactions,
            [],
            {
              #userId: userId,
              #format: format,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>> exportAccounts({
    required String? userId,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAccounts,
          [],
          {
            #userId: userId,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ExportResult>(
          this,
          Invocation.method(
            #exportAccounts,
            [],
            {
              #userId: userId,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>> exportBudgets({
    required String? userId,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportBudgets,
          [],
          {
            #userId: userId,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ExportResult>(
          this,
          Invocation.method(
            #exportBudgets,
            [],
            {
              #userId: userId,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>> exportCategories({
    required String? userId,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportCategories,
          [],
          {
            #userId: userId,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ExportResult>(
          this,
          Invocation.method(
            #exportCategories,
            [],
            {
              #userId: userId,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ExportResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ExportResult>>> exportAllData({
    required String? userId,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAllData,
          [],
          {
            #userId: userId,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ExportResult>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ExportResult>>(
          this,
          Invocation.method(
            #exportAllData,
            [],
            {
              #userId: userId,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ExportResult>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>> importTransactions({
    required String? userId,
    required String? filePath,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importTransactions,
          [],
          {
            #userId: userId,
            #filePath: filePath,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ImportResult>(
          this,
          Invocation.method(
            #importTransactions,
            [],
            {
              #userId: userId,
              #filePath: filePath,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>> importAccounts({
    required String? userId,
    required String? filePath,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importAccounts,
          [],
          {
            #userId: userId,
            #filePath: filePath,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ImportResult>(
          this,
          Invocation.method(
            #importAccounts,
            [],
            {
              #userId: userId,
              #filePath: filePath,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>> importBudgets({
    required String? userId,
    required String? filePath,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importBudgets,
          [],
          {
            #userId: userId,
            #filePath: filePath,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ImportResult>(
          this,
          Invocation.method(
            #importBudgets,
            [],
            {
              #userId: userId,
              #filePath: filePath,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>> importCategories({
    required String? userId,
    required String? filePath,
    required _i6.ExportFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importCategories,
          [],
          {
            #userId: userId,
            #filePath: filePath,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ImportResult>(
          this,
          Invocation.method(
            #importCategories,
            [],
            {
              #userId: userId,
              #filePath: filePath,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ImportResult>>);
}
